### ISSUE TITLE
提供了一个去除调试器的版本

### ISSUE THREAD

**Issue by JianxinMa** [a1exwang/v9.js#2]
见 https://github.com/JianxinMa/v9.js/commit/b7c75bcf40693830ded304164054f4d984ce7c1e 这条commit对ssets/js/cpu.js的修改。
要运行去除debugger的版本，就把3956行的runNonStop改成指向runNonDebug。

你可能需要修改server.js，使它符合你的需求。

**Comment by JianxinMa** [comment]
用这个版本的话，step、continue就都不能用（会出错，请小心）。

**Comment by a1exwang** [comment]
ok, 我一会试一下

---

发件人: JianxinMa notifications@github.com
发送时间: 2016年5月16日 11:57
收件人: a1exwang/v9.js
主题: [a1exwang/v9.js] 提供了一个去除调试器的版本 (#2)

见 JianxinMa@b7c75bchttps://github.com/JianxinMa/v9.js/commit/b7c75bcf40693830ded304164054f4d984ce7c1e 这条commit对ssets/js/cpu.js的修改。
要运行去除debugger的版本，就把3956行的runNonStop改成指向runNonDebug。

你可能需要修改server.js，使它符合你的需求。

―
