### ISSUE TITLE
调试信息格式

### ISSUE THREAD

**Issue by JianxinMa** [a1exwang/v9.js#3]
我写了个关于调试信息中的类型信息的文档。你看看那个伪代码，看看能不能理解我用的格式。
https://github.com/JianxinMa/v9.js/blob/master/doc/debugger.md
一直拉到Debugging Information那里开始看就可以了。

**Comment by JianxinMa** [comment]
你看看现在的说明足不足够你生成调试信息。有不清楚的给我发个issue吧。

**Comment by JianxinMa** [comment]
这个是我生成的调试信息 https://raw.githubusercontent.com/JianxinMa/v9.js/to_be_removed/server/de
这份信息把多份代码的调试信息cat在了一起。

**Comment by a1exwang** [comment]
ok下午搞
